"""init core exam schema

Revision ID: 62125dd14faa
Revises: 
Create Date: 2026-04-03 08:04:52.622429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62125dd14faa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('semester', sa.Text(), nullable=True),
    sa.Column('exam_type', sa.Text(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='paper_status'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_min >= 0', name='ck_papers_duration_non_negative'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 100)', name='ck_papers_quality_score_range'),
    sa.CheckConstraint('question_count >= 0', name='ck_papers_question_count_non_negative'),
    sa.CheckConstraint('total_score >= 0', name='ck_papers_total_score_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_course_id'), 'papers', ['course_id'], unique=False)
    op.create_index(op.f('ix_papers_created_by'), 'papers', ['created_by'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('course_id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='exercise_status'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('duration_min IS NULL OR duration_min >= 0', name='ck_exercises_duration_non_negative'),
    sa.CheckConstraint('total_score >= 0', name='ck_exercises_total_score_non_negative'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_course_id'), 'exercises', ['course_id'], unique=False)
    op.create_index(op.f('ix_exercises_created_by'), 'exercises', ['created_by'], unique=False)
    op.create_index(op.f('ix_exercises_paper_id'), 'exercises', ['paper_id'], unique=False)
    op.create_table('paper_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('score_each', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('question_count >= 0', name='ck_paper_sections_question_count_non_negative'),
    sa.CheckConstraint('score_each >= 0', name='ck_paper_sections_score_each_non_negative'),
    sa.CheckConstraint('section_order >= 1', name='ck_paper_sections_order_positive'),
    sa.CheckConstraint('total_score >= 0', name='ck_paper_sections_total_score_non_negative'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'section_order', name='uq_paper_sections_paper_order')
    )
    op.create_index(op.f('ix_paper_sections_paper_id'), 'paper_sections', ['paper_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'GRADED', name='attempt_status'), nullable=False),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='ck_exercise_attempts_score_non_negative'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise_id', 'student_id', name='uq_exercise_attempts_exercise_student')
    )
    op.create_index(op.f('ix_exercise_attempts_exercise_id'), 'exercise_attempts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_attempts_student_id'), 'exercise_attempts', ['student_id'], unique=False)
    op.create_table('paper_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Text(), nullable=True),
    sa.CheckConstraint('order_num >= 1', name='ck_paper_questions_order_positive'),
    sa.CheckConstraint('score >= 0', name='ck_paper_questions_score_non_negative'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['paper_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'order_num', name='uq_paper_questions_paper_order')
    )
    op.create_index(op.f('ix_paper_questions_paper_id'), 'paper_questions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_questions_section_id'), 'paper_questions', ['section_id'], unique=False)
    op.create_table('exercise_attempt_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_option', sa.Text(), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('awarded_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.CheckConstraint('awarded_score IS NULL OR awarded_score >= 0', name='ck_attempt_answers_awarded_score_non_negative'),
    sa.ForeignKeyConstraint(['attempt_id'], ['exercise_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['paper_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_exercise_attempt_answers_attempt_question')
    )
    op.create_index(op.f('ix_exercise_attempt_answers_attempt_id'), 'exercise_attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_exercise_attempt_answers_question_id'), 'exercise_attempt_answers', ['question_id'], unique=False)
    op.create_table('paper_question_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('option_key', sa.Text(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['paper_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'option_key', name='uq_paper_question_options_key')
    )
    op.create_index(op.f('ix_paper_question_options_question_id'), 'paper_question_options', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_question_options_question_id'), table_name='paper_question_options')
    op.drop_table('paper_question_options')
    op.drop_index(op.f('ix_exercise_attempt_answers_question_id'), table_name='exercise_attempt_answers')
    op.drop_index(op.f('ix_exercise_attempt_answers_attempt_id'), table_name='exercise_attempt_answers')
    op.drop_table('exercise_attempt_answers')
    op.drop_index(op.f('ix_paper_questions_section_id'), table_name='paper_questions')
    op.drop_index(op.f('ix_paper_questions_paper_id'), table_name='paper_questions')
    op.drop_table('paper_questions')
    op.drop_index(op.f('ix_exercise_attempts_student_id'), table_name='exercise_attempts')
    op.drop_index(op.f('ix_exercise_attempts_exercise_id'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_paper_sections_paper_id'), table_name='paper_sections')
    op.drop_table('paper_sections')
    op.drop_index(op.f('ix_exercises_paper_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_by'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_course_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_papers_created_by'), table_name='papers')
    op.drop_index(op.f('ix_papers_course_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
